version: "3.8"

services:
  jellyfin:
    image: linuxserver/jellyfin
    container-name: jellyfin
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    ports:
      - "8096:8096"
    volumes:
      - ./config/jellyfin:/config
      - ./data/media/series:/series
      - ./data/media/movies:/movies
    restart: unless-stopped
    networks:
      - media-stack
  # Jellyseerr - For browsing and requesting media
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    ports:
      - "5055:5055"
    volumes:
      - ./config/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - media-stack

  # Prowlarr - Manages your torrent indexers and syncs them to other apps
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    volumes:
      - ./config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - media-stack

  # Sonarr - TV Show Manager
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    volumes:
      - ./config/sonarr:/config
      - ./data/media/series:/series
      - ./data/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media-stack

  # Radarr - Movie Manager
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    volumes:
      - ./config/radarr:/config
      - ./data/media/movies:/movies
      - ./data/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - media-stack

  # FlareSolverr - Solves Cloudflare challenges for Prowlarr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - media-stack

  

  # Decypharr for TorBox use with *arrs
  decypharr:
    image: cy01/blackhole:latest
    container_name: decypharr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    ports:
      - "8282:8282"
    volumes:
      - ./data/downloads:/downloads
      - ./mounts/:/mounts/
      - /mnt/:/mnt:rshared
      - ./config/decypharr:/app
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    networks:
      - media-stack

  # TorBox Media Center
  torbox-media-center:
    image: anonymoussystems/torbox-media-center:latest
    container_name: torbox-media-center
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    cap_add:
      - SYS_ADMIN
      - MKNOD
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/macfuse0:/dev/fuse
      - /dev/macfuse1
      - /dev/macfuse2
      - /dev/macfuse3
    volumes:
      - ./mounts/torbox:/torbox
    environment:
      - TORBOX_API_KEY=a38c94d2-25a2-4868-8060-cc8741858391
      - MOUNT_METHOD=fuse
      - MOUNT_PATH=/torbox

# This network allows all the containers to talk to each other by name
networks:
  media-stack:
    driver: bridge
