name: torbox-media-center
services:
    torbox-media-center:
        container_name: torbox-media-center
        stdin_open: true
        tty: true
        restart: always
        volumes:
            - /home/$(whoami)/torbox:/torbox
        environment:
            - TORBOX_API_KEY=<EDIT_THIS_KEY>
            - MOUNT_METHOD=strm
            - MOUNT_PATH=/torbox
        image: anonymoussystems/torbox-media-center:main